# Netlify configuration for Videntify UI

[build]
  base = "ui/"
  command = "npm run build"
  publish = "build"
  node_version = "20"

# Environment variables
[build.environment]
  CI = "false"
  NODE_ENV = "production"

# Define redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define headers - simplified for troubleshooting
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Define asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Simplify processing
[functions]
  node_bundler = "esbuild"

# Define plugins to disable for troubleshooting
[plugins]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false
