# Netlify configuration for Videntify UI

[build]
  base = "ui"
  command = "npm run build"
  publish = "build"

# Define redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define headers - simplified for troubleshooting
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Define asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
