version: '3.5'

services:
  milvus-connector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milvus-connector
    ports:
      - "5050:5050"
    environment:
      - MILVUS_HOST=host.docker.internal
      - MILVUS_PORT=19530
      - DEBUG=true
    volumes:
      - ../docker_milvus_connector.py:/app/connector.py
    command: ["python", "/app/connector.py", "--debug"]
    restart: always
    network_mode: "bridge"

  # The Milvus infrastructure (standalone, etcd, minio) is managed separately
  # and we assume it's already running
