name: Check Netlify Secrets

on:
  workflow_dispatch:
    
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          if [ -n "${{ secrets.NETLIFY_SITE_ID }}" ]; then
            echo "✅ NETLIFY_SITE_ID is set"
            echo "NETLIFY_SITE_ID length: ${#NETLIFY_SITE_ID}"
          else
            echo "❌ NETLIFY_SITE_ID is empty"
            exit 1
          fi
          
          if [ -n "${{ secrets.NETLIFY_STAGING_SITE_ID }}" ]; then
            echo "✅ NETLIFY_STAGING_SITE_ID is set"
            echo "NETLIFY_STAGING_SITE_ID length: ${#NETLIFY_STAGING_SITE_ID}"
          else
            echo "❌ NETLIFY_STAGING_SITE_ID is empty" 
            exit 1
          fi
          
          if [ -n "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
            echo "✅ NETLIFY_AUTH_TOKEN is set"
            echo "NETLIFY_AUTH_TOKEN length: ${#NETLIFY_AUTH_TOKEN}"
          else
            echo "❌ NETLIFY_AUTH_TOKEN is empty"
            exit 1
          fi
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_STAGING_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      - name: Validate Netlify token format
        if: always()
        run: |
          if [[ $NETLIFY_AUTH_TOKEN == *"netlify"* ]]; then
            echo "✅ NETLIFY_AUTH_TOKEN appears to be in the expected format"
          else
            echo "⚠️ NETLIFY_AUTH_TOKEN may not be in the expected format"
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      - name: Check Site ID formats
        if: always()
        run: |
          if [[ ${#NETLIFY_SITE_ID} -gt 10 ]]; then
            echo "✅ NETLIFY_SITE_ID has an appropriate length"
          else
            echo "⚠️ NETLIFY_SITE_ID seems too short"
          fi
          
          if [[ ${#NETLIFY_STAGING_SITE_ID} -gt 10 ]]; then
            echo "✅ NETLIFY_STAGING_SITE_ID has an appropriate length"
          else
            echo "⚠️ NETLIFY_STAGING_SITE_ID seems too short"
          fi
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_STAGING_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}
