name: Verify Netlify Secrets

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets existence
        run: |
          echo "Checking if NETLIFY_SITE_ID exists"
          if [ -n "${{ secrets.NETLIFY_SITE_ID }}" ]; then
            echo "✅ NETLIFY_SITE_ID exists"
          else
            echo "❌ NETLIFY_SITE_ID is missing"
          fi
          
          echo "Checking if NETLIFY_STAGING_SITE_ID exists"
          if [ -n "${{ secrets.NETLIFY_STAGING_SITE_ID }}" ]; then
            echo "✅ NETLIFY_STAGING_SITE_ID exists"
          else
            echo "❌ NETLIFY_STAGING_SITE_ID is missing"
          fi
          
          echo "Checking if NETLIFY_AUTH_TOKEN exists"
          if [ -n "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
            echo "✅ NETLIFY_AUTH_TOKEN exists"
          else
            echo "❌ NETLIFY_AUTH_TOKEN is missing"
          fi
